# Based on the issue template
name: Bug report
description: Create a report to help us improve
title: "[BUG] <title>"
labels: [Bug]
body:
  - type: markdown
    attributes:
      value: |
# DEPRECATION NOTICE 
This image is deprecated. We will not offer support for this image and it will not be updated.


Overseerr has now merged with Jellyseerr, we recommend migrating to the official Seerr image: https://github.com/seerr-team/seerr
