#!/usr/bin/with-contenv bash
# shellcheck shell=bash

export CONFIG_DIRECTORY="/config"

if [[ -z ${LSIO_NON_ROOT_USER} ]]; then
    exec \
        s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost 5055" \
            cd /app/overseerr s6-setuidgid abc /usr/bin/yarn start
else
    exec \
        s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost 5055" \
            cd /app/overseerr /usr/bin/yarn start
fi
